### ISSUE TITLE
Web UI

### ISSUE THREAD

**Issue by MrFlynn** [MrFlynn/voyager#1]
## Description
Web UI that has a search box and returns a list of results for a query. Should return 10 results per page and have some pagination method.

## Tasks
- [x] Text search page.
- [x] Results view page.
- [x] Send query string in URL to search backend.
  - [x] Optional `after`/offset for pagination.
