### ISSUE TITLE
Backend Searcher

### ISSUE THREAD

**Issue by MrFlynn** [MrFlynn/voyager#2]
## Description
Indexes directory of files using Lucene searcher. Declares an API endpoint that returns a list of 10 results per request, depending on the (optional) offset parameter.

## Tasks
- [x] Ingest files into Lucene index.
  - Potentially multithread this? Depends on how slow it is to ingest 2GB of results.
- [x] Build Index.
  - [x] Create representation of files in the index (title, body, description snippet, URL, etc.).
    -  [x] Serialize this into JSON.
- [x] Search API endpoint.
  - [x] Accept query string and/or optional offset parameter(s).
  - [x] Return list of ordered results (includes URL, title, description).
