### ISSUE TITLE
PageRank

### ISSUE THREAD

**Issue by MrFlynn** [MrFlynn/voyager#4]
## Description
Replace built-in indexer with PageRank algorithm.

## Tasks
- [ ] Figure out how to integrate this with Lucene.
- [ ] Build PageRank algorithm
- [ ] Integrate with rest of application to be able to change ranking algorithm at startup or have an option in the web UI to specify what algorithm you want.
